### PR TITLE
Added Support for ESP32-S2 & ESP-S3, configurable frequency and radians

### PR DESCRIPTION
**Pull request by mikaeltulldahl**
This is fork from @h2zero incorporating a fix for ESP32-S2 which turned out to also fix the same problem for ESP32-S3, where the resolution was configured to too high in ledcSetup.

The changes are only tested on an ESP32-S3-DevKitC-1.
This should solve issue #18.

Added this functionality:
* Configurable frequency
    * Defaults to 50 hz
    * Also tested at 333hz which is common for modern servos.
* Users can now instantiate ServoFloat and ServoDouble in addition to Servo.
    * This is to allow using radians, which would get truncated with integers. Also when using degrees this is beneficial if you want better resolution than 1 degree.
    * The implementation must be in the header file for template classes.
    * ServoBase class is shared between all template versions of ServoTemplate, so the static variable channel_next_free is shared.
    * Added an example for how to use ServoFloat with radians.

### CODE REVIEW

**Comment by mikaeltulldahl** [comment]
Hello @JarekParal is it possible to get this merged?

**Review by JarekParal — APPROVED** [review]

**Comment by JarekParal** [comment]
@mikaeltulldahl Hello, thank you very much for your PR. All the changes seems to be good. I merged it and I'm going to release it as version 1.1

**Comment by mikaeltulldahl** [comment]
Great! If possible, could you also publish the update on PlatformIO with `pio pkg publish`?

**Comment by JarekParal** [comment]
Do you know if the automatic update of PlatformIO libraries still works or it has to be done with `pio pkq publish`?

**Comment by mikaeltulldahl** [comment]
I think it is a manual step. I see you did a release here on github but it
didn't became available on PlatformIO

**Comment by JarekParal** [comment]
The automatic update from GitHub Release is still working:
image

**Comment by mikaeltulldahl** [comment]
Ah yes, my mistake

**Pull request merged**
